extends Node

const GAME_IN_PROGRESS = "GAME_IN_PROGRESS"
const GAME_OVER = "GAME_OVER"
const GAME_STARTING = "GAME_STARTING"
const GAME_UPGRADING = "GAME_UPGRADING"
const MASS_MAX: float = 100.0
const SAFE_RADIUS: float = 1500.0
const SAFE_RADIUS_LOSE_TIME: float = 5.0

enum MODULE_TYPES {
  ENGINE,
  WEAPON,
  MISC,
}
